'use client';

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertTriangle } from 'lucide-react';

interface AIDisclaimerProps {
  variant?: 'warning' | 'inline';
}

export function AIDisclaimer({ variant = 'warning' }: AIDisclaimerProps) {
  if (variant === 'inline') {
    return (
      <div className="flex items-center gap-2 text-sm text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/30 px-3 py-2 rounded-md border border-amber-200 dark:border-amber-800 border-dashed">
        <AlertTriangle className="h-4 w-4 flex-shrink-0" />
        <span className="font-medium">AI Draft - Review before use</span>
      </div>
    );
  }

  return (
    <Alert variant="destructive" className="bg-amber-50 border-amber-300 dark:bg-amber-950/30 dark:border-amber-800">
      <AlertTriangle className="h-4 w-4 text-amber-600" />
      <AlertTitle className="text-amber-800 dark:text-amber-200">AI-Generated Content</AlertTitle>
      <AlertDescription className="text-amber-700 dark:text-amber-300">
        This content was generated by AI and must be reviewed and verified by a physician before use.
        Do not copy directly to EMR without verification. AI may produce inaccurate or incomplete information.
      </AlertDescription>
    </Alert>
  );
}
